### ISSUE TITLE
job_id is null when using matrix strategy

### ISSUE THREAD

**Issue by andrei-ivanov-pie** [Tiryoh/gha-jobid-action#13]
This action works perfectly well when we have a single workflow. However, when I try to use this action with matrix strategy to kick off a workflow, the job_id ends up null.
`    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
         var: [values]
      uses: other workflow.yml
`

**Comment by Tiryoh** [comment]
How about specifying job_name like `job_name: build-and-deploy (${{ matrix.ros-distro }}, ${{ matrix.arch }})`?

https://github.com/Tiryoh/docker-ros2-desktop-vnc/blob/8115cc026c9123c7c98c5e50207c8d60905c1775/.github/workflows/deploy.yml#L99-L104

job_name must be named the same as the list of jobs in the actions summary page.

![image](https://user-images.githubusercontent.com/3256629/195157518-784bd645-61a5-4ec6-b413-71a0fc292bb6.png)

**Comment by Tiryoh** [comment]
Feel free to re-open this issue when you have any updates.
