### ISSUE TITLE
replace set-output commands which will be deprecated

### ISSUE THREAD

**Issue by Tiryoh** [Tiryoh/gha-jobid-action#16]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by phoeniixhawk** [comment]
Great plugin btw,  I think we can fix this with
```
echo "job_id=${job_id}" >> $GITHUB_OUTPUT
echo "html_url=${html_url}" >> $GITHUB_OUTPUT
```

**Comment by Tiryoh** [comment]
Hi @phoeniixdotcom, 
Thanks for your report!
If you don't mind, could you send me a PR?

**Comment by phoeniixhawk** [comment]
Sure, but I'm getting permission denied to push a feature branch.  Could you give me rights?

**Comment by phoeniixhawk** [comment]
Oh, nevermind, initiated PR from my acct.  Thx!
