### ISSUE TITLE
ISSUE: Run without docker

### ISSUE THREAD

**Issue by matanbaruch** [Tiryoh/gha-jobid-action#29]
Using Docker Hub can cause rate limiting due to Alpine pull

I think this is a very simple bash script. No need to do docker build for this.

![image](https://github.com/Tiryoh/gha-jobid-action/assets/36934912/95b2ef54-bda2-4d72-8232-2999760f6b98)

**Comment by Tiryoh** [comment]
Oh...

It seems that using GitHub Actions' composite action, we can implement it without using Docker. I don't remember the details, but perhaps at the time this action was released, it might have been a choice between Node.js and Docker.

https://github.blog/changelog/2021-08-25-github-actions-reduce-duplication-with-action-composition/

**Comment by Tiryoh** [comment]
I have made changes to use GitHub Composite Actions in #30.

Could you try using `Tiryoh/gha-jobid-action@v1` instead of `Tiryoh/gha-jobid-actionv0`?

**Comment by Tiryoh** [comment]
I have updated and addressed in #30. Please feel free to reopen this issue.
